#+TITLE: Awesome config
#+AUTHOR: BoT_Nikos

* Icons
This config uses feather icons. You can find it
in the icons folder

* Autostart
This file runs everytime after reloading awesome and
do things such as setting up wallpapers, starting compositor and a few more

* Colors
File for import to other files, that contains current colors of window manager.
Temporary solution. All colors need to be in theme file.

* Widgets

** Sidebar

Little widget that opens sidebar on pressing
mod4-i or by mouse clicking on special wibar icon.

Here you can change some settings of system, and
see common state of things.

Sidebar includes the following widgets:

*** [[./widgets/systemResources.lua][Resources]]

Shows current state of system resources.
CPU get data from *mpstat* command

*** [[./widgets/player.lua][Player]]

Here you can control your current playback of
choosed player.

Widget requires *playerctl* console utility
to skip, toggle tracks and curl to downloading images.
Images downloading in tmp directory.

*** [[./widgets/monitorToggler.lua][Screen control]]

This widget currently can toggle your monitor from 'left-of' mode to
'mirror-mode' and back.

 - [ ] Better chosing of monitors positions

*** [[./widgets/compositorToggler.lua][Compositor control]]

This widget allows you to toggle your compositor.
Currently works only with compfy.

*** [[./widgets/power.lua][Power control]]

Allows you to reboot, shutdown and logout from your current session.

